db = "appdata.db"
level = "B1"
anki = ""
ocr_models = "/home/morti/models/"
ai_chat = "gpt"
ai_role = ""
ai_preamble = ""
scraper_sleep = 500

[ai_chats.gpt]
name = "Chat GPT"
url = "https://api.openai.com/v1"
model = "gpt-5"
key = "[enter API key here]"
provider = "Openai"
ndims = 2232

[window]
width = 1400.0
height = 800.0
split = 0.6499999761581421
font_size = 18.0
lang = "Polski"
theme = "Catppuccin Mocha"
settings_label_w = 200.0
spacing = 2.0
padding = 5.0
padding_frame = 20.0

[keys]
elevenlabs = ""
deepl = ""
