BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Documents" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Title"	NUMERIC NOT NULL,
	"Content"	BLOB,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Notes" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Line"	INTEGER NOT NULL,
	"Character"	INTEGER,
	"Document"	INTEGER NOT NULL,
	"Content"	TEXT,
	PRIMARY KEY("Id" AUTOINCREMENT),
	FOREIGN KEY("Document") REFERENCES "Notes"
);
INSERT INTO "Documents" VALUES (1,'Test','Test document');
INSERT INTO "Notes" VALUES (1,1,3,1,'Test annotation');
COMMIT;
